create table if not exists public.services (id uuid primary key default gen_random_uuid(), owner_id uuid references public.platform_users(id) on delete cascade, title text not null, description text not null, category text not null, package_type text default 'starter', price_cents int default 0, delivery_days int default 7, portfolio_urls text[] default '{}', is_active boolean default true, ai_optimized_description text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.service_orders (id uuid primary key default gen_random_uuid(), service_id uuid references public.services(id) on delete set null, buyer_id uuid references public.platform_users(id) on delete set null, seller_id uuid references public.platform_users(id) on delete set null, status text default 'novo', amount_cents int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.portfolio_items (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete cascade, title text not null, description text, url text, media_urls text[] default '{}', skills text[] default '{}', created_at timestamptz default now());

create table if not exists public.matches (id uuid primary key default gen_random_uuid(), challenge_id uuid references public.challenges(id) on delete cascade, student_id uuid references public.platform_users(id) on delete cascade, mentor_id uuid references public.platform_users(id) on delete set null, client_id uuid references public.platform_users(id) on delete set null, compatibility_score numeric(5,2) default 0, reasons jsonb default '[]', risks jsonb default '[]', status text default 'sugerido', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.compatibility_scores (id uuid primary key default gen_random_uuid(), match_id uuid references public.matches(id) on delete cascade, criteria text not null, score numeric(5,2) not null, weight numeric(5,2) not null, explanation text, created_at timestamptz default now());
create table if not exists public.projects (id uuid primary key default gen_random_uuid(), challenge_id uuid references public.challenges(id) on delete set null, match_id uuid references public.matches(id) on delete set null, student_id uuid references public.platform_users(id) on delete set null, mentor_id uuid references public.platform_users(id) on delete set null, client_id uuid references public.platform_users(id) on delete set null, title text not null, scope text not null, status public.project_status default 'match', value_cents int default 0, due_date date, progress smallint default 0 check(progress between 0 and 100), evidence_urls text[] default '{}', ai_next_steps text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.project_milestones (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete cascade, title text not null, description text, due_date date, status text default 'pendente', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.deliverables (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete cascade, title text not null, description text, file_urls text[] default '{}', status text default 'enviado', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.reviews (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete cascade, reviewer_id uuid references public.platform_users(id) on delete set null, reviewed_id uuid references public.platform_users(id) on delete set null, rating smallint check(rating between 1 and 5), comment text, created_at timestamptz default now());

