create table if not exists public.conversations (id uuid primary key default gen_random_uuid(), type public.conversation_type default 'projeto', title text not null, project_id uuid references public.projects(id) on delete cascade, created_by uuid references public.platform_users(id) on delete set null, metadata jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.conversation_participants (conversation_id uuid references public.conversations(id) on delete cascade, user_id uuid references public.platform_users(id) on delete cascade, role text default 'member', created_at timestamptz default now(), primary key(conversation_id,user_id));
create table if not exists public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid references public.conversations(id) on delete cascade, sender_id uuid references public.platform_users(id) on delete set null, body text not null, attachment_urls text[] default '{}', ai_generated boolean default false, created_at timestamptz default now());

create table if not exists public.transactions (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete set null, payer_id uuid references public.platform_users(id) on delete set null, amount_cents int not null, currency text default 'BRL', stripe_payment_intent_id text, status public.transaction_status default 'pendente', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.revenue_splits (id uuid primary key default gen_random_uuid(), transaction_id uuid references public.transactions(id) on delete cascade, beneficiary_id uuid references public.platform_users(id) on delete set null, label text check(label in ('aluno','mentor','plataforma','impacto')), percent numeric(5,2) not null, amount_cents int not null, created_at timestamptz default now());
create table if not exists public.wallets (user_id uuid primary key references public.platform_users(id) on delete cascade, available_cents int default 0, pending_cents int default 0, lifetime_cents int default 0, updated_at timestamptz default now());
create table if not exists public.withdrawals (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete cascade, amount_cents int not null, status text default 'solicitado', pix_key text, created_at timestamptz default now(), updated_at timestamptz default now());

