create table if not exists public.benefits (id uuid primary key default gen_random_uuid(), title text not null, description text not null, category text not null, eligibility_rules jsonb default '{}', is_active boolean default true, created_at timestamptz default now());
create table if not exists public.user_benefits (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete cascade, benefit_id uuid references public.benefits(id) on delete cascade, status text default 'ativo', created_at timestamptz default now());
create table if not exists public.human_scores (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete cascade, communication numeric(5,2) default 0, reliability numeric(5,2) default 0, delivery_quality numeric(5,2) default 0, learning_evolution numeric(5,2) default 0, impact numeric(5,2) default 0, total numeric(5,2) default 0, explanation text, created_at timestamptz default now());
create table if not exists public.impact_metrics (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete set null, title text not null, metric_type text not null, value numeric(12,2) default 0, unit text not null, ods text[] default '{}', evidence_url text, created_at timestamptz default now());
create table if not exists public.impact_fund (id uuid primary key default gen_random_uuid(), transaction_id uuid references public.transactions(id) on delete set null, amount_cents int not null, destination text default 'fundo_circular', status text default 'reservado', created_at timestamptz default now());

create table if not exists public.evidences (id uuid primary key default gen_random_uuid(), title text not null, description text, evidence_type text not null, source_url text, file_urls text[] default '{}', related_table text, related_id uuid, tags text[] default '{}', created_by uuid references public.platform_users(id) on delete set null, created_at timestamptz default now());
create table if not exists public.validation_interviews (id uuid primary key default gen_random_uuid(), profile text not null, interviewee_name text, interviewee_contact text, summary text not null, pains text[] default '{}', objections text[] default '{}', willingness_to_pay text, consent_given boolean default false, created_at timestamptz default now());
create table if not exists public.lois (id uuid primary key default gen_random_uuid(), company_name text not null, contact_name text, contact_email text, interest_summary text not null, estimated_value_cents int default 0, status text default 'rascunho', file_url text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.pilots (id uuid primary key default gen_random_uuid(), title text not null, partner text, objective text, status text default 'planejado', start_date date, end_date date, results jsonb default '{}', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.pitch_assets (id uuid primary key default gen_random_uuid(), title text not null, asset_type text not null, content text, file_url text, version int default 1, created_at timestamptz default now());

create table if not exists public.contracts (id uuid primary key default gen_random_uuid(), project_id uuid references public.projects(id) on delete set null, client_id uuid references public.platform_users(id) on delete set null, student_id uuid references public.platform_users(id) on delete set null, mentor_id uuid references public.platform_users(id) on delete set null, terms text not null, status text default 'rascunho', signed_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists public.consents (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete cascade, consent_type text not null, granted boolean default true, version text default '1.0', ip_address text, user_agent text, created_at timestamptz default now());
create table if not exists public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.platform_users(id) on delete set null, action text not null, entity_table text, entity_id uuid, metadata jsonb default '{}', created_at timestamptz default now());
create table if not exists public.ai_logs (id uuid primary key default gen_random_uuid(), user_id uuid references public.platform_users(id) on delete set null, mode text not null, prompt text not null, response text not null, model text, created_at timestamptz default now());
create table if not exists public.embeddings_index (id uuid primary key default gen_random_uuid(), entity_table text not null, entity_id uuid not null, content text not null, embedding vector(1536), created_at timestamptz default now());

